server:
  port: 8190
  servlet:
    context-path: /web-market-analytics
utils:
  cart:
    prefix: SPRING_WEB_APP_
integrations:
  cart-service:
    url: http://localhost:5555/cart
  core-service:
    url: http://localhost:5555/core
